### ISSUE TITLE
Banning is not working

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/ImmaFreedomMod#16]
We experience a serious problem.
Banning is not working, not even permban.

@OutOfYourMind @LegendIsAwesomes @OxLemonxO please respond as fast as possible.

**Comment by LegendIsAwesomes** [comment]
Is there any logs?

**Comment by aggelosQQ** [comment]
No, we ban them and they just rejoin.
It happens on every ban, even auto ejects.

**Comment by aggelosQQ** [comment]
@JeromSar can you help?

**Comment by tylerhyperHD** [comment]
I volunteer to help fix this issue.

**Comment by OutOfYourMind** [comment]
Tyler, added to the github repo. Please fix it.

**Comment by OutOfYourMind** [comment]
@tylerhyperHD Added to the github repo, please fix.

**Comment by tylerhyperHD** [comment]
I just checked all the code and after doing so I believe that someone has corrupted the ban config. Simply delete both ban configs and try again. I deem this as invalid as a plugin-related cause.

**Comment by OutOfYourMind** [comment]
@tylerhyperHD Didn't work.

**Comment by tylerhyperHD** [comment]
Can you please give me the full error that appears on console?

**Comment by OutOfYourMind** [comment]
17.10 14:34:03 [Server] INFO [CONSOLE_COMMAND] CONSOLE: /doom awesomepinch
17.10 14:34:03 [Server] INFO CONSOLE - Casting oblivion over AwesomePinch
17.10 14:34:03 [Server] INFO AwesomePinch will be completely obliviated!
17.10 14:34:03 [Server] INFO CONSOLE - Removing AwesomePinch from the superadmin list.
17.10 14:34:03 [Server] INFO AwesomePinch blew up
17.10 14:34:03 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 20.424768396026614, 0.0)
17.10 14:34:03 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 19.937873416151746, 0.0)
17.10 14:34:03 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 19.46071632658759, 0.0)
17.10 14:34:03 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 18.993102369713668, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 18.534840683058196, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 18.085744221395185, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 17.645629680399598, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,-0.07840000152587834,0.0 (0.0, 17.214317421829406, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 16.79163140020399, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 16.377399090948984, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 15.971451419978225, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 15.573622694684042, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 15.183750536307763, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 14.801675813662786, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 14.427242578183213, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 14.060298000271484, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 13.700692306919077, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 13.348278720574784, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 13.002913399235622, 0.0)
17.10 14:34:04 [Server] WARN AwesomePinch moved too quickly! 0.0,0.0,0.0 (0.0, 12.664455377735921, 0.0)
17.10 14:34:06 [Server] INFO CONSOLE - Banning AwesomePinch, IP: 68.54.251.248
17.10 14:34:06 [Server] INFO [EXIT] AwesomePinch left the game.
17.10 14:34:06 [Disconnect] User AwesomePinch has disconnected, reason: FUCKOFF, and get your shit together!
17.10 14:34:07 [Server] INFO [EXIT] AwesomePinch left the game.
17.10 14:34:07 [Server] INFO AwesomePinch left the game.
17.10 14:34:07 [Server] WARN handleDisconnection() called twice
17.10 14:34:11 [Server] ERROR Could not pass event ServerListPingEvent to ImmaFreedomMod v4.3
17.10 14:34:11 [Server] INFO org.bukkit.event.EventException
17.10 14:34:11 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusListener.a(PacketStatusListener.java:106) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:23) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:8) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:124) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:325) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:1) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280) [ProtocolLib.jar:?]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at net.minecraft.server.v1_8_R2.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:11 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Multicraft] Skipped 18 lines due to rate limit (30/s)
17.10 14:34:21 [Server] ERROR Could not pass event ServerListPingEvent to ImmaFreedomMod v4.3
17.10 14:34:21 [Server] INFO org.bukkit.event.EventException
17.10 14:34:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusListener.a(PacketStatusListener.java:106) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:23) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:8) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:124) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:325) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:1) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280) [ProtocolLib.jar:?]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at net.minecraft.server.v1_8_R2.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:21 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Multicraft] Skipped 66 lines due to rate limit (30/s)
17.10 14:34:23 [Server] ERROR Could not pass event ServerListPingEvent to ImmaFreedomMod v4.3
17.10 14:34:23 [Server] INFO org.bukkit.event.EventException
17.10 14:34:23 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusListener.a(PacketStatusListener.java:106) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:23) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:8) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:124) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:325) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:1) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280) [ProtocolLib.jar:?]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at net.minecraft.server.v1_8_R2.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:23 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Multicraft] Skipped 18 lines due to rate limit (30/s)
17.10 14:34:26 [Server] ERROR Could not pass event ServerListPingEvent to ImmaFreedomMod v4.3
17.10 14:34:26 [Server] INFO org.bukkit.event.EventException
17.10 14:34:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusListener.a(PacketStatusListener.java:106) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:23) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.PacketStatusInStart.a(SourceFile:8) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:124) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:325) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.NetworkManager.channelRead0(NetworkManager.java:1) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$4.channelRead(NettyChannelInjector.java:280) [ProtocolLib.jar:?]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at net.minecraft.server.v1_8_R2.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:26 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-870264a-0a645a2]
17.10 14:34:31 [Multicraft] Skipped 18 lines due to rate limit (30/s)
17.10 14:34:31 [Server] INFO UUID of player AwesomePinch is 3b8a1507-fef8-3011-8f51-8c86e69ee578
17.10 14:34:31 [Server] INFO [ImmaFreedomMod] Obtaining UUID for new player: AwesomePinch
17.10 14:34:31 [Server] INFO [JOIN] AwesomePinch (deadbeef-53f9-1f2f-22c6-b6a19bc0af51) joined the game with IP address: 68.54.251.248
17.10 14:34:31 [Server] INFO AwesomePinch is an Developer
17.10 14:34:31 [Connect] User AwesomePinch, IP 68.54.251.248
17.10 14:34:31 [Multicraft] AwesomePinch ran command Message of the Day

**Comment by tylerhyperHD** [comment]
Thank you for that, i'll look into it.

**Comment by aggelosQQ** [comment]
Thank you Tyler.

**Comment by tylerhyperHD** [comment]
@OutOfYourMind I don't have perms to commit lol

**Comment by OxLemonxO** [comment]
the problem is, the server is using spigot r0.1 while tfm is r0.3
TFM_ServerInterface, is used in ServerListPingEvent, has these imports:
import net.minecraft.server.v1_8_R3.EntityPlayer;
import net.minecraft.server.v1_8_R3.MinecraftServer;
import net.minecraft.server.v1_8_R3.PropertyManager;
probably the cause of this problem

**Comment by JeromSar** [comment]
@OxLemonxO TFM should warn you at startup if that's the cause of the problem.

**Comment by tylerhyperHD** [comment]
the revision of spigot hasn't changed in awhile so that's not the problem at all.

**Comment by OutOfYourMind** [comment]
Issue fixed.
